version: '3.7'

networks:
  LEMP:

services:
  nginx:
    image: nginx
    container_name: LEMP_nginx
    restart: always
    ports:
      - 9191:80
    links:
      - php
    volumes:
      - './etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template'
      - './etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './src:/var/www/html'
    command: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
    networks:
      - LEMP

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: LEMP_phpmyadmin
      restart: always
      environment:
        PMA_HOST: LEMP_mysql
      ports:
        - '9192:80'
      links:
        - database
      networks:
      - LEMP

  database:
    image: mysql:5.7
    container_name: LEMP_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '9193:3306'
    volumes:
      - './etc/db:/var/lib/mysql'
    networks:
      - LEMP

  php:
    image: nanoninja/php-fpm
    container_name: LEMP_php
    restart: always
    ports:
      - '9194:9000'
    volumes:
      - './src:/var/www/html'
      - './etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    networks:
      - LEMP
    links:
      - database