version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: LEAMP74_phpmyadmin
    restart: always
    environment:
      PMA_HOST: LEAMP74_mysql
    links:
      - database
    ports:
      - 9192:80

  database:
    image: mysql:5.7
    container_name: LEAMP74_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - './docker/db:/var/lib/mysql'
      - './log/mysql/:/var/log/mysql/'
    ports:
      - 9193:3306

  php:
    build: ./docker/lamp74
    container_name: LEAMP74_php
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=0
    volumes:
      - './src:/var/www/html'
      - './log/apache2/:/var/log/apache2/'
    links:
      - database
    ports:
      - 80:80
